`timescale 1ns/1ps

// ============================================================
// tb_cnn_feature_extractor_all_top.v
//
// Project:
//   FPGA CNN Fatigue Monitoring
//
// Verification goal:
//   Verify the FPGA accelerator side of a Python + FPGA
//   co-processing fatigue monitoring system.
//
// System role split:
//   Python:
//     - camera input
//     - OpenCV frame handling
//     - MediaPipe FaceMesh
//     - ROI extraction
//     - EAR / MAR / PERCLOS
//     - logging
//     - final fatigue decision
//
//   FPGA:
//     - parallel CNN-style feature extraction
//     - process left_eye, right_eye, and mouth ROI inputs
//     - generate 18 features per ROI
//
// This testbench reads ROI HEX files generated by Python:
//   ../mem/left_eye.hex
//   ../mem/right_eye.hex
//   ../mem/mouth.hex
//
// Then it runs the RTL accelerator and writes:
//   ../mem/fpga_features_left_eye.txt
//   ../mem/fpga_features_right_eye.txt
//   ../mem/fpga_features_mouth.txt
//
// These outputs are compared with Python golden_model.py.
// ============================================================

module tb_cnn_feature_extractor_all_top;

    reg clk;
    reg rst;
    reg start;

    wire busy;
    wire done;

    wire [575:0] left_features;
    wire [575:0] right_features;
    wire [575:0] mouth_features;

    cnn_feature_extractor_all_top #(
        .LEFT_MEM_FILE("../mem/left_eye.hex"),
        .RIGHT_MEM_FILE("../mem/right_eye.hex"),
        .MOUTH_MEM_FILE("../mem/mouth.hex")
    ) dut (
        .clk(clk),
        .rst(rst),
        .start(start),

        .busy(busy),
        .done(done),

        .left_features(left_features),
        .right_features(right_features),
        .mouth_features(mouth_features)
    );

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    integer fout_left;
    integer fout_right;
    integer fout_mouth;
    integer i;

    initial begin
        rst = 1'b1;
        start = 1'b0;

        fout_left  = $fopen("../mem/fpga_features_left_eye.txt", "w");
        fout_right = $fopen("../mem/fpga_features_right_eye.txt", "w");
        fout_mouth = $fopen("../mem/fpga_features_mouth.txt", "w");

        if (fout_left == 0) begin
            $display("ERROR: cannot open left output file");
            $stop;
        end

        if (fout_right == 0) begin
            $display("ERROR: cannot open right output file");
            $stop;
        end

        if (fout_mouth == 0) begin
            $display("ERROR: cannot open mouth output file");
            $stop;
        end

        #50;
        rst = 1'b0;

        #30;
        start = 1'b1;
        #10;
        start = 1'b0;

        $display("FPGA accelerator verification started...");
        $display("Python-generated ROI inputs:");
        $display("../mem/left_eye.hex");
        $display("../mem/right_eye.hex");
        $display("../mem/mouth.hex");

        wait(done == 1'b1);

        $display("FPGA accelerator verification finished.");
        $display("============================================================");

        $display("LEFT EYE FEATURES");
        for (i = 0; i < 18; i = i + 1) begin
            $display("left feature[%0d] = %d", i, left_features[i*32 +: 32]);
            $fdisplay(fout_left, "%d", left_features[i*32 +: 32]);
        end

        $display("------------------------------------------------------------");

        $display("RIGHT EYE FEATURES");
        for (i = 0; i < 18; i = i + 1) begin
            $display("right feature[%0d] = %d", i, right_features[i*32 +: 32]);
            $fdisplay(fout_right, "%d", right_features[i*32 +: 32]);
        end

        $display("------------------------------------------------------------");

        $display("MOUTH FEATURES");
        for (i = 0; i < 18; i = i + 1) begin
            $display("mouth feature[%0d] = %d", i, mouth_features[i*32 +: 32]);
            $fdisplay(fout_mouth, "%d", mouth_features[i*32 +: 32]);
        end

        $display("============================================================");
        $display("FPGA accelerator output files saved:");
        $display("../mem/fpga_features_left_eye.txt");
        $display("../mem/fpga_features_right_eye.txt");
        $display("../mem/fpga_features_mouth.txt");
        $display("Compare them with python_features_*.txt using Python golden_model.py");

        $fclose(fout_left);
        $fclose(fout_right);
        $fclose(fout_mouth);

        #100;
        $stop;
    end

endmodule
